server {
    listen 8000;

    # Povolíme jen určitou IP adresu - toto bude Docker container IP
    # Toto zabrání jednoduchému spuštění na localhostu
    # Skutečnou IP adresu Docker containeru je potřeba zjistit při spuštění

    location / {
        # Ověření autorizace pomocí hlavičky
        if ($http_x_team_secret != "${TEAM_SECRET_KEY}") {
            return 403;
        }

        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Nastavení CORS - povoleno jen pro určité domény
    add_header 'Access-Control-Allow-Origin' 'null' always;
    add_header 'Access-Control-Allow-Methods' 'GET' always;
}